/*
 * timing.cpp
 *
 *  Created on: Oct 9, 2012
 *      Author: benk
 */

#include <raven/util/timing.h>

#undef TIMING_STRUCT_FIELD
#define TIMING_STRUCT_FIELD(name) TIMING_STRUCT_FIELD_SOURCE(TimingInfo,name)
#undef TIMING_STRUCT_SETUP
#define TIMING_STRUCT_SETUP(StructName) TIMING_STRUCT_SETUP_SOURCE(StructName)

TIMING_STRUCT_SETUP(TimingInfo)

TIMING_STRUCT_FIELD(overall)

TIMING_STRUCT_FIELD(usb_read)
TIMING_STRUCT_FIELD(state_machine)
TIMING_STRUCT_FIELD(update_state)
TIMING_STRUCT_FIELD(control)
TIMING_STRUCT_FIELD(usb_write)
TIMING_STRUCT_FIELD(ros)

#undef TIMING_STRUCT_FIELD
#define TIMING_STRUCT_FIELD(name) TIMING_STRUCT_FIELD_SOURCE(USBTimingInfo,name)
#undef TIMING_STRUCT_SETUP
#define TIMING_STRUCT_SETUP(StructName) TIMING_STRUCT_SETUP_SOURCE(StructName)

TIMING_STRUCT_SETUP(USBTimingInfo)

TIMING_STRUCT_FIELD(get_packet)
TIMING_STRUCT_FIELD(process_packet)

#undef TIMING_STRUCT_NAME
#define TIMING_STRUCT_NAME ControlTiming
#undef TIMING_STRUCT_SETUP
#define TIMING_STRUCT_SETUP(sn) TIMING_STRUCT_SETUP_SOURCE(TIMING_STRUCT_NAME)
#undef TIMING_STRUCT_FIELD
#define TIMING_STRUCT_FIELD(name) TIMING_STRUCT_FIELD_SOURCE(TIMING_STRUCT_NAME,name)

TIMING_STRUCT_SETUP(ControlTiming)

TIMING_STRUCT_FIELD(overall)
