#!/usr/bin/env python
import roslib

roslib.load_manifest('raven_2_vision')
import rospy
from geometry_msgs.msg import PoseArray
import tf
import optparse

class ObjectMarkerEstimator:
	def __init__(self,topic):
		self.topic = topic
		self.pose_array_topic = topic + '/poses'
		self.stamp_param = topic + '/ids_stamp'
		self.ids_param = topic + '/ids'